/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartVisualization: typeof import('./src/components/ResultPage/ChartVisualization.vue')['default']
    DataGroupingCard: typeof import('./src/components/MainPage/DataGroupingCard.vue')['default']
    EnhancedChartVisualization: typeof import('./src/components/ResultPage/EnhancedChartVisualization.vue')['default']
    HeatmapChart: typeof import('./src/components/ResultPage/charts/HeatmapChart.vue')['default']
    HistogramChart: typeof import('./src/components/ResultPage/charts/HistogramChart.vue')['default']
    KeyOrderingSettings: typeof import('./src/components/Settings/KeyOrderingSettings.vue')['default']
    MeasurementInfo: typeof import('./src/components/ResultPage/MeasurementInfo.vue')['default']
    MeasurementPoints: typeof import('./src/components/ResultPage/MeasurementPoints.vue')['default']
    MeasurementPointsSelector: typeof import('./src/components/ResultPage/MeasurementPointsSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedGroupsCard: typeof import('./src/components/MainPage/SavedGroupsCard.vue')['default']
    ScatterChart: typeof import('./src/components/ResultPage/charts/ScatterChart.vue')['default']
    SearchHistoryCard: typeof import('./src/components/MainPage/SearchHistoryCard.vue')['default']
    SearchSection: typeof import('./src/components/MainPage/SearchSection.vue')['default']
    SiteAveragesChart: typeof import('./src/components/ResultPage/charts/SiteAveragesChart.vue')['default']
    StatisticalInfo: typeof import('./src/components/ResultPage/StatisticalInfo.vue')['default']
    StatisticalInfoByPoints: typeof import('./src/components/ResultPage/StatisticalInfoByPoints.vue')['default']
    StatisticalScatterChart: typeof import('./src/components/ResultPage/charts/StatisticalScatterChart.vue')['default']
    SummaryDataTable: typeof import('./src/components/ResultPage/SummaryDataTable.vue')['default']
    ViewHistoryCard: typeof import('./src/components/MainPage/ViewHistoryCard.vue')['default']
    WaferHeatmapChart: typeof import('./src/components/ResultPage/charts/WaferHeatmapChart.vue')['default']
  }
}
